### ISSUE TITLE
TweakReg crashes when updatehdr is set True

### ISSUE THREAD

**Issue by sphy2016** [spacetelescope/notebooks#143]
I was try to align a group of drizzled images to GAIA catalog. When I set the updatehdr to true to update the header, the program failed and return a error.

> Traceback (most recent call last):
>   File "/Users/apple/opt/anaconda3/envs/astroconda/lib/python3.6/site-packages/drizzlepac/util.py", line 225, in wrapper
>     result = func(*args, **kwargs)
>   File "/Users/apple/opt/anaconda3/envs/astroconda/lib/python3.6/site-packages/drizzlepac/tweakreg.py", line 586, in run
>     reusename=uphdr_par['reusename'])
>   File "/Users/apple/opt/anaconda3/envs/astroconda/lib/python3.6/site-packages/drizzlepac/imgclasses.py", line 797, in updateHeader
>     wcscorr.init_wcscorr(self._im.hdu)
>   File "/Users/apple/opt/anaconda3/envs/astroconda/lib/python3.6/site-packages/stwcs/wcsutil/wcscorr.py", line 113, in init_wcscorr
>     wcsext.data.field(key)[rownum] = wcshdr[(key + wkey)[:8]]
>   File "/Users/apple/opt/anaconda3/envs/astroconda/lib/python3.6/site-packages/astropy/io/fits/header.py", line 148, in __getitem__
>     card = self._cards[self._cardindex(key)]
>   File "/Users/apple/opt/anaconda3/envs/astroconda/lib/python3.6/site-packages/astropy/io/fits/header.py", line 1708, in _cardindex
>     raise KeyError(f"Keyword {keyword!r} not found.")
> KeyError: "Keyword 'CTYPE1O' not found."

**Comment by catherine-martlin** [comment]
Hello @sphy2016 - thanks for reporting this! Do you remember which notebook you were working with when this occurred?
